# https://docs.docker.com/compose/compose-file/
# docker-compose

version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - my_network
  hello-world:
    container_name: hello-world
    image: go-hello-world:1.1
    ports:
      - 3000:8080
    networks:
      - my_network
    environment:
      - WEIRD_WORD="i'm white juggernaut"
    depends_on:
      - redis

networks:
  my_network:
    name: my_network